package com.inspirecoding.supershopper.utils

import com.inspirecoding.supershopper.R

val listOfDefaultCategories = listOf(
    Pair(0, R.string.alcoholic_drinks),
    Pair(1, R.string.baby_products),
    Pair(2, R.string.bakery),
    Pair(4, R.string.beverages),
    Pair(9, R.string.canned_foods),
    Pair(10, R.string.car_care_products),
    Pair(15, R.string.clothes),
    Pair(16, R.string.coffee_tea_and_hot_chocolate),
    Pair(17, R.string.condiments),
    Pair(19, R.string.cosmetics),
    Pair(21, R.string.dairy_products),
    Pair(22, R.string.diet_foods),
    Pair(25, R.string.electronics_devices),
    Pair(57, R.string.fish_and_seafood),
    Pair(26, R.string.frozen),
    Pair(46, R.string.grains_and_pasta),
    Pair(39, R.string.home_and_kitchen),
    Pair(3, R.string.home_baking),
    Pair(36, R.string.house_cleaning_products),
    Pair(40, R.string.meat_pourly_and_sausages),
    Pair(42, R.string.newspapers),
    Pair(43, R.string.office_supplies),
    Pair(44, R.string.oils),
    Pair(62, R.string.other),
    Pair(64, R.string.personal_hygiene),
    Pair(47, R.string.pet_care),
    Pair(48, R.string.pharmacy),
    Pair(50, R.string.preserves),
    Pair(51, R.string.ready_meals),
    Pair(59, R.string.snacks),
    Pair(60, R.string.spices),
)